# Generated by Django 4.2.13 on 2024-07-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_breed_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=15)),
                ('favoritefood', models.CharField(max_length=30)),
                ('favoritetoy', models.CharField(max_length=50)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.breed')),
            ],
        ),
    ]
