# Generated by Django 4.2.13 on 2024-07-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='todoapp.breed'),
        ),
    ]
